### PR TITLE
v1.5.9

### LINKED ISSUE #98: Missing 'style.load' event support ?
How can I use the 'style.load' event : [https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:style.load](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:style.load) ?

### LINKED ISSUE #99: Issues with peer dependencies when updating to version 1.5.8
I ran the "update" pnpm command to update all outdated packages, but I found peer dependency errors when doing so:

image

### LINKED ISSUE #105: Property 'setConfigProperty' does not exist on type 'Map'.ts(2339)
image

nuxt-mapbox version 1.5.8. Need to change the card color to 'dusk'

### PR DESCRIPTION
**Pull request by AlexLavoie42**
closes #99
closes #98 
closes #105

### CODE REVIEW

**Review by SterpaWan — APPROVED** [review]

**Comment by duncanhall** [comment]
@AlexLavoie42 is this blocked waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68640 to get merged? Is there anything I can do to help get this released?

**Comment by AlexLavoie42** [comment]
Unfortunately I have been running into this build error even after updating the types:
`error TS7016: Could not find a declaration file for module 'mapbox-gl'. '/home/runner/work/Nuxt-Mapbox/Nuxt-Mapbox/node_modules/.pnpm/mapbox-gl@3.1.2/node_modules/mapbox-gl/dist/mapbox-gl.js' implicitly has an 'any' type.`

I assumed this was caused by the outdated types but now I cannot find the problem.

**Comment by duncanhall** [comment]
Not sure if it adds any more info, but VS code had this offer:

Screenshot 2024-02-28 at 16 21 36

There are also [anecdotal suggestions on StackOverflow](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam) of this being related to `package.json` settings which sort of match the VSCode suggesting.

I can't see anything obvious in https://github.com/mapbox/mapbox-gl-js/blob/main/package.json that has changed/needs fixing but it feels like the issue may be dependent on changes there?

**Comment by AlexLavoie42** [comment]
> Having re-read this I'm wondering actually if the `@types/mapbox-gl` `package.json` needs updating to have the definition file recognised correctly?

This is exactly what I thought at first. Unfortunately I have already done this in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68640 which has now been merged. It seems like updating does not make the error go away.

One thing I have noticed is that after the update only the types for version [3.1.0](https://www.npmjs.com/package/@types/mapbox-gl/v/3.1.0) got published, when from what I can tell it should have automatically done 3.1.2 instead. It could be that I have done something wrong in the types update.

> I can't see anything obvious in https://github.com/mapbox/mapbox-gl-js/blob/main/package.json that has changed/needs fixing but it feels like the issue may be dependent on changes there?

I have a feeling this is the cause as well but I could not find anything. One thing I need to test is if the error goes away if I downgrade mapbox-gl back to 2.x. I have a feeling it may be related to a package.json change in mapbox-gl done during 2.x -> 3.x

**Pull request merged**
