### PR TITLE
Fix custom geocoder async import

### PR DESCRIPTION
**Pull request by ElvisGmz**

### CODE REVIEW

**Comment by AlexLavoie42** [comment]
Could you describe what issue this is meant to fix? Originally the import happened on mount, however I changed it to avoid not displaying the geocoder for a while after the page has loaded.

**Comment by AlexLavoie42** [comment]
If you visit [the playground](https://stackblitz.com/github/AlexLavoie42/Nuxt-Mapbox?file=playground%2Fpages%2Fgeocode.vue) and go to `/geocode` you can see an example of the geocoder working. Would you be able to try and reproduce what is happening on your environment there?
The easiest way to do this is usually to copy small parts of your project over (removing any sensitive info) until the issue appears.

Also, are you using the latest version of the module? (v1.4.3)

**Comment by AlexLavoie42** [comment]
So the issue is coming from the import running on the server side when it should only be loaded on the client side. This can be simply fixed by doing `if (process.client)` before the import. I will update the PR and merge.

Thank you for contributing and bringing the issue to my attention!

**Comment by ElvisGmz** [comment]
Thank you very much @AlexLavoie42 🫡🎉

**Pull request merged**
